# Generated by Django 5.0.6 on 2024-05-22 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='Facebook',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='Instagram',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='Whatsapp',
        ),
        migrations.AddField(
            model_name='setting',
            name='facebook',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='instagram',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='whatsapp',
            field=models.TextField(blank=True),
        ),
    ]
