# Generated by Django 5.0.6 on 2024-05-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_setting_facebook_remove_setting_instagram_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categorie',
        ),
        migrations.AlterField(
            model_name='setting',
            name='coordinate',
            field=models.TextField(verbose_name='координаты'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='linkMap',
            field=models.TextField(verbose_name='ссылка на карту'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='logo',
            field=models.ImageField(upload_to='', verbose_name='лого'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='numberAdmin',
            field=models.CharField(max_length=15, verbose_name='номер админа'),
        ),
    ]
