# Generated by Django 5.0.6 on 2024-05-31 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_messageforadmin_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterModelOptions(
            name='categorie',
            options={'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='messageforadmin',
            options={'verbose_name_plural': 'Сообщение для админа'},
        ),
        migrations.AlterModelOptions(
            name='setting',
            options={'verbose_name_plural': 'Настройки сайта'},
        ),
    ]
