# Generated by Django 5.0.6 on 2024-05-31 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_book_options_alter_categorie_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setting',
            options={},
        ),
    ]
