# Generated by Django 5.0.6 on 2024-06-01 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_setting_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='coordinate',
            new_name='address',
        ),
    ]
